GET http://localhost:5081/

###
# @name loginRequest
POST http://localhost:5081/auth/login
content-type: application/json

{
    "Email": "admin@store.com",
    "Password": "admin123"
}

###
@authToken = {{loginRequest.response.body.token}}

###
POST http://localhost:5081/categories
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "Name": "Apparel"
}

###
POST http://localhost:5081/products
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "Name": "Shirt",
    "Price": 15.99,
    "CategoryId": 4
}